services:
  - type: web
    name: phonebook-be
    runtime: node
    buildCommand: npm install && NODE_OPTIONS=--max-old-space-size=512 npm run build
    startCommand: NODE_OPTIONS=--max-old-space-size=512 npm run start:prod
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: 1d
      - key: ADMIN_EMAIL
        sync: false
